server:
  port: 8003

#mybatis配置
mybatis:
  type-aliases-package: com.wang.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db03?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  #Eureka配置
eureka:
  client:
    service-url:
      #服务发布地址
      #单机发布 defaultZone: http://localhost:7001/eureka/
      #模拟集群发布地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8003
  info:
    app.name: wangsen-springcloud
    company.name: aspire.com